import javax.swing.JOptionPane;

/**
 *
 * @author Jacobo
 */
public class TragaMonedas extends javax.swing.JFrame {

    /**
     * Creates new form TragaMonedas
     */
    public TragaMonedas() {
        initComponents();
        a = new Proceso(Ranura1.getSize());        
        Ranura1.add(a);
        Ranura1.repaint();   
        b = new Proceso(Ranura2.getSize());        
        Ranura2.add(b);
        Ranura2.repaint(); 
        c = new Proceso(Ranura3.getSize());        
        Ranura3.add(c);
        Ranura3.repaint();   
        d = new Proceso(Ranura4.getSize());        
        Ranura4.add(d);
        Ranura4.repaint(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Ranura1 = new javax.swing.JLabel();
        Ranura2 = new javax.swing.JLabel();
        Ranura3 = new javax.swing.JLabel();
        Ranura4 = new javax.swing.JLabel();
        girar = new javax.swing.JButton();
        premio = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 51, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Ranura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icono1.jpg"))); // NOI18N

        Ranura2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icono2.jpg"))); // NOI18N

        Ranura3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icono3.jpg"))); // NOI18N

        Ranura4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icono4.jpg"))); // NOI18N

        girar.setBackground(new java.awt.Color(51, 153, 255));
        girar.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        girar.setForeground(new java.awt.Color(255, 255, 255));
        girar.setText("GIRAR");
        girar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girarActionPerformed(evt);
            }
        });

        premio.setEditable(false);
        premio.setBackground(new java.awt.Color(102, 51, 255));
        premio.setBorder(null);
        premio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premioActionPerformed(evt);
            }
        });

        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/titulo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(premio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(girar, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(titulo)
                        .addGap(328, 328, 328))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Ranura1)
                        .addGap(24, 24, 24)
                        .addComponent(Ranura2)
                        .addGap(26, 26, 26)
                        .addComponent(Ranura3)
                        .addGap(38, 38, 38)
                        .addComponent(Ranura4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(titulo)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ranura1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ranura3)
                    .addComponent(Ranura4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ranura2)
                        .addGap(9, 9, 9)))
                .addGap(54, 54, 54)
                .addComponent(girar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(premio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void girarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girarActionPerformed
        // TODO add your handling code here:
        if (girar.getText().equals("GIRAR")){
            girar.setText("PARAR");
            a.startAnimation(); d.startAnimation(); b.startAnimation(); c.startAnimation();
            premio.setText("");
        }
        else
        {
            a.stopAnimation(); b.stopAnimation(); c.stopAnimation(); d.stopAnimation();
            
            if (a.getIm() == b.getIm() && b.getIm() == c.getIm() && c.getIm() == d.getIm()){
                JOptionPane.showMessageDialog(null, "Felicidades has ganado");
            }else{
                JOptionPane.showMessageDialog(null, "Sigue intentando");
            }
           
            
            
            girar.setText("GIRAR");
    }//GEN-LAST:event_girarActionPerformed
    }
    private void premioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_premioActionPerformed

    /**
     * @param args the command line arguments
     */
    Proceso a ; 
    Proceso b ;
    Proceso c ; 
    Proceso d ;
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TragaMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TragaMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TragaMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TragaMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TragaMonedas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ranura1;
    private javax.swing.JLabel Ranura2;
    private javax.swing.JLabel Ranura3;
    private javax.swing.JLabel Ranura4;
    private javax.swing.JButton girar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField premio;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
